spring.application.name=sales-manager
#DATASOURCE
spring.datasource.url= jdbc:mysql://localhost:3307/sales_manager_db?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password= &XTwpmcHs%%5X577Y%7ETVdpFD^CgnJ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#JPA
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true
spring.jpa.open-in-view= true